name: Check Repository Structure

on:
  push:
    branches:
    - main

jobs:
  check-directories:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # List all files and directories in the repository
    - name: List repository contents
      run: |
        echo "Repository root contents:"
        ls -la
        
        echo "\nRecursively listing all directories:"
        find . -type d -not -path "./node_modules/*" -not -path "./.git/*" | sort