name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # Temporarily removing cache to avoid integrity issues
        # cache: 'npm'
    
    - name: Clear npm cache and install dependencies
      run: |
        npm cache clean --force
        npm install --no-audit --prefer-offline=false
    
    - name: Build
      run: npm run build
      env:
        REACT_APP_GEODB_API_KEY: ${{ secrets.REACT_APP_GEODB_API_KEY }}
    
    - name: Debug directory content
      run: |
        echo "Current directory:"
        ls -la
        echo "Build directory:"
        ls -la build || echo "Build directory doesn't exist!"
    
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'
        SOURCE_DIR: 'build'